### ISSUE TITLE
Strip Wasm File

### ISSUE THREAD

**Issue by daxpedda** [mtolmacs/wasm2map#11]
I was wondering if it's in scope to let `wasm2map` optionally strip the Wasm file after generating the sourcemap file.

This is useful to reduce the file size, as the information should be unnecessary when using the sourcemap anyway.
It might still be useful to retain it for environments that don't support sourcemaps but instead support the embedded DWARF information.

**Comment by mtolmacs** [comment]
I think stripping should be delegated to other tools and it should be an explicit choice on the user's part. There are tools which can do a much better job and wasm2map would duplicate that effort without any real benefit.

That being said, let's keep this ticket open for a documentation change to call out the fact that the DWARF data can be stripped if the user wants to optimize the WASM file size.

**Comment by mtolmacs** [comment]
There is a project within Chrome to support DWARF debugging for WebAssembly directly: https://developer.chrome.com/blog/wasm-debugging-2020/

So this might not be something which should be done automatically. Whether this should be a function wasm2map offers, I'm still leaning toward no, just to keep the tool singularly focused on one task, generating a sourcemap for WASM files from DWARF debug symbols.

I added a note about stripping with a tool recommendation to the (admittedly rudimentary) repo wiki, so I'm closing this issue.

**Comment by daxpedda** [comment]
> There is a project within Chrome to support DWARF debugging for WebAssembly directly: https://developer.chrome.com/blog/wasm-debugging-2020/

I've tried the extension described here and it works quite well, no sourcemap needed.
But Chrome also supports sourcemaps without any extension.

I think the reason why it would still make sense to strip is because this is duplicate information. You either want DWARF **or** sourcemap, as far as I can tell there is no benefit of having both.
