### ISSUE TITLE
How to show original local variable name?

### ISSUE THREAD

**Issue by oliverzy** [mtolmacs/wasm2map#28]
Hi,

The tool is great. The callstack and breakpoint works perfectly in Chrome. But it seems that it cannot show original local variable name correctly.
![image](https://github.com/user-attachments/assets/c0d9000c-86b5-41ae-98b7-08e884caa636)

Is it possible to fix, that's the last piece I think we currently lack?
if it isn't supported now, could you point a direction that maybe I'm happy to contribute.

**Comment by mtolmacs** [comment]
Hi @oliverzy, the original focus was on function names and call stack, but if I recall correctly, you could collect the original variable names from the DWARF info and add it to the sourcemap `names` section, which in theory would work in the Chrome debugger.

Of course if you come up with a solution I'd love to see your PR as this is indeed a big missing piece.

**Comment by oliverzy** [comment]
Hi @mtolmacs，

After some investigation, maybe we should follow this documentation  
https://github.com/tc39/source-map/blob/main/proposals/scopes.md
to generate scope related fields.

I still need some time to figure out how to do this.

**Comment by oliverzy** [comment]
Hi @mtolmacs,

After looking into this issue a little deeper, I found it's not possible to implement this only by sourcemap, because rustc maintains a logic call stack in wasm memory, chrome debugger simply show wasm local variable. They are not the same.

The way to fix this issue is creating a chrome dev tools language extension plugin and put dwarf debuginfo in the sourcemap, and then during the debug session, devtools will call into our plugin, the plugin can use debuginfo to construct the correct the scope and binding to the debugger.

I think it's possible to do but require a lot of effort.

**Comment by mtolmacs** [comment]
> Hi @mtolmacs,
> 
> After looking into this issue a little deeper, I found it's not possible to implement this only by sourcemap, because rustc maintains a logic call stack in wasm memory, chrome debugger simply show wasm local variable. They are not the same.

I'm not sure I follow. Are you saying that during debug compilation the local variables are renamed to `$var<number>`? Even in [debug lvl 2](https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo)?

> The way to fix this issue is creating a chrome dev tools language extension plugin and put dwarf debuginfo in the sourcemap, and then during the debug session, devtools will call into our plugin, the plugin can use debuginfo to construct the correct the scope and binding to the debugger.

This is out of scope for this project. In this case, if you can use Chrome, [using DWARF debug info directly is a better way to do it](https://developer.chrome.com/docs/devtools/wasm/).

> 
> I think it's possible to do but require a lot of effort.

This is not the right direction for this lib. If you want to delve deeper anyway you can follow these steps to verify there is truly no path forward:

1. Research if other WASM toolchains can generate sourcemaps which resolve variable names. Maybe a C/C++ toolchain can already do it.
2. Verify that a hand-crafted sourcemap can resolve local variable names, i.e firefox and chrome devtools indeed resolve the names from sourcemap for WASM. If the devtool support is not there, then there is no point in going forward.
3. Check if the generated DWARF info indeed contain the local variable resolutions
4. Implement an in-scope translation from DWARF -> sourcemap v3.

**Comment by oliverzy** [comment]
![image](https://github.com/user-attachments/assets/f3576658-c7b2-4484-8bc9-75d94ad9d622)
I have drawn this picture to show the issue more precisely.
You can see both the variable count and name don't match, and the display value of the variable are not pretty as well.

I agree that this feature is out of the scope for this project, but anyway I would like to express my gratitude for the great work you have done.

**Comment by oliverzy** [comment]
I would like to create a new project that use wasm2map as a library to generate base sourcemap, and then generate additional debug info from dwarf debuginfo section to be able to reconstruct scope and variable binding during debug session.
And then put these into another file.
And finally write a devtools language extension to hook into debug session to provide these information to the debugger.

It's ok to close this issue for now.
