### ISSUE TITLE
Doesn't take `DW_AT_stmt_list` into account

### ISSUE THREAD

**Issue by daxpedda** [mtolmacs/wasm2map#8]
I'm not entirely sure if `gimli`/`object` actually supports reading this, but not taking this into account produces wrong paths.

I will try and take a stab at this later.

**Comment by mtolmacs** [comment]
Thanks for looking into it!

Taking a cursory look at the GIMLI repo, it does recognize `DW_AT_stmt_list` at the [unit level](https://github.com/gimli-rs/gimli/blob/c42dec01df24d9a5cdbdd8ca1aea555242cc64e9/src/read/dwarf.rs#L906) and it does[ incorporate it as an offset](https://github.com/gimli-rs/gimli/blob/c42dec01df24d9a5cdbdd8ca1aea555242cc64e9/src/read/dwarf.rs#L951) in the `line_program` property on the unit. LineProgramHeader is then [inited with that offset](https://github.com/gimli-rs/gimli/blob/c42dec01df24d9a5cdbdd8ca1aea555242cc64e9/src/read/dwarf.rs#L951).

Do you happen to have a WASM which demonstrates the issue? I think that would be a good first step.

**Comment by daxpedda** [comment]
Any Rust program compiling with std has this problem already.
```rust
fn main() { panic!("Hello, World!"); }
```
... is enough to reproduce this issue.
